# Generated by Django 4.1.3 on 2022-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=256, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('price', models.FloatField(help_text='Введите цену товара', verbose_name='Цена')),
            ],
        ),
    ]
