# Generated by Django 4.1.3 on 2022-11-19 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_discount_name_alter_tax_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(default=0, help_text='Выберите скидку', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order', to='items.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(help_text='Выберите товар', related_name='order', to='items.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(default=0, help_text='Выберите налоговую ставку', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order', to='items.tax', verbose_name='Налог'),
        ),
    ]
