# Generated by Django 4.1.3 on 2022-11-20 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_discount_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value_percent',
            field=models.PositiveSmallIntegerField(help_text='Введите значение в %', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Значение %'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='value_percent',
            field=models.PositiveSmallIntegerField(help_text='Введите значение в %', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Значение %'),
        ),
    ]
